
export const AppTranslations = {
    en: {
        'en': 'English',
        'ru': 'Русский',
        'EXAMPLES.FOCUSABLE_DESCRIPTION': 'allows to navigate over focusable controls using arrow keys',
        'EXAMPLES.PRESS': 'Press',
        'EXAMPLES.TO_CHOOSE_CARD': 'to choose list and',
        'EXAMPLES.TO_CHANGE_FOCUSABLE_ELEMENTS': 'buttons to change focusable elements in list',
        'EXAMPLES.FOCUSABLE_ELEMENT': 'Focusable element',
        'EXAMPLES.SELECTED_DESCRIPTION': 'allows to navigate over non-focuseable elements using arrow keys',
        'EXAMPLES.INFINITE_SCROLL_DESCRIPTION': 'allows to upload data in chunks while user is scrolling',
        'EXAMPLES.DRAGGABLE_DESCRIPTION': 'implements drag & drop functionality',
        'EXAMPLES.SELECTED.DISABLED': 'Disable selection',
        'EXAMPLES.SHORTCUTS_DESCRIPTION': 'allows you to configure local and global shortcuts (hotkeys)',
        'EXAMPLES.HOTKEYS_DESCRIPTION': 'allows you to configure local and global hotkeys',
        'EXAMPLES.HOTKEYS.LANGUAGE_CHANGE': 'Change language',
        'EXAMPLES.HOTKEYS.STATE_CHANGE': 'Change state',
        'EXAMPLES.HOTKEYS.CHANGE_BACKGROUND': 'Change background',
        'EXAMPLES.HOTKEYS.CHANGE_FOREGROUND': 'Change foreground',
    },
    ru: {
        'en': 'English',
        'ru': 'Русский',
        'EXAMPLES.FOCUSABLE_DESCRIPTION': 'позволяет перемещаться по фокусируемым элементам управления с помощью клавиш со стрелками',
        'EXAMPLES.PRESS': 'Нажмите',
        'EXAMPLES.TO_CHOOSE_CARD': 'для выбора списка и',
        'EXAMPLES.TO_CHANGE_FOCUSABLE_ELEMENTS': 'кнопки для переключения между фокусируемыми элементами списка',
        'EXAMPLES.FOCUSABLE_ELEMENT': 'Фокусируемый элемент',
        'EXAMPLES.SELECTED_DESCRIPTION': 'позволяет перемещаться по нефокусируемым элементам управления с помощью клавиш со стрелками',
        'EXAMPLES.INFINITE_SCROLL_DESCRIPTION': 'позволяет загружать данные частями во время прокрутки пользователя',
        'EXAMPLES.DRAGGABLE_DESCRIPTION': 'реализация функции перетаскивания (drag & drop)',
        'EXAMPLES.SELECTED.DISABLED': 'Запретить смену элемента',
        'EXAMPLES.HOTKEYS_DESCRIPTION': 'позволяет настроить локальные и глобальные горячие клавиши',
        'EXAMPLES.HOTKEYS.LANGUAGE_CHANGE': 'Сменить язык',
        'EXAMPLES.HOTKEYS.STATE_CHANGE': 'Сменить состояние',
        'EXAMPLES.HOTKEYS.CHANGE_BACKGROUND': 'Сменить цвет фона',
        'EXAMPLES.HOTKEYS.CHANGE_FOREGROUND': 'Сменить цвет текста',
    }
};
